# -*- coding: utf-8 -*-
"""day6.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C81GMnuuoF_wbQ_c-ta1PvgV6ebEgkdy
"""

import nltk
import spacy
from nltk.corpus import stopwords
nltk.download('stopwords')
nlp = spacy.load('en_core_web_sm')
text = "This is another example text to demonstrate the use of NLTK and Spacy."
text = text.lower()
doc = nlp(text)
stop_words = set(stopwords.words('english'))
filtered_text = [token.text for token in doc if token.text not in stop_words]
filtered_text = ' '.join(filtered_text)
print("Original Text:", text)
print("Filtered Text:", filtered_text)